
const data = {
  products: [
      {
        "id": "1",
        "name": "Bermuda 1",
        "slug": "bermuda-1",
        "size": "M",
        "quantity": 10,
        "category": "Bermudas",
        "image": "/products/bermuda01.jpg",
        "price": 79.99,
        "description": "Bermuda 1 com estilo moderno e confortável.",
        "rating": 4.5
      },
      {
        "id": "2",
        "name": "Bermuda 2",
        "slug": "bermuda-2",
        "size": "M",
        "quantity": 11,
        "category": "Bermudas",
        "image": "/products/bermuda02.jpg",
        "price": 84.99,
        "description": "Bermuda 2 com estilo moderno e confortável.",
        "rating": 4.6
      },
      {
        "id": "3",
        "name": "Bermuda 3",
        "slug": "bermuda-3",
        "size": "M",
        "quantity": 12,
        "category": "Bermudas",
        "image": "/products/bermuda03.jpg",
        "price": 89.99,
        "description": "Bermuda 3 com estilo moderno e confortável.",
        "rating": 4.7
      },
      {
        "id": "4",
        "name": "Bermuda 4",
        "slug": "bermuda-4",
        "size": "M",
        "quantity": 13,
        "category": "Bermudas",
        "image": "/products/bermuda04.jpg",
        "price": 94.99,
        "description": "Bermuda 4 com estilo moderno e confortável.",
        "rating": 4.8
      },
      {
        "id": "5",
        "name": "Bermuda 5",
        "slug": "bermuda-5",
        "size": "M",
        "quantity": 14,
        "category": "Bermudas",
        "image": "/products/bermuda05.jpg",
        "price": 99.99,
        "description": "Bermuda 5 com estilo moderno e confortável.",
        "rating": 4.9
      },
      {
        "id": "6",
        "name": "Bermuda 6",
        "slug": "bermuda-6",
        "size": "M",
        "quantity": 15,
        "category": "Bermudas",
        "image": "/products/bermuda06.jpg",
        "price": 104.99,
        "description": "Bermuda 6 com estilo moderno e confortável.",
        "rating": 4.5
      },
      {
        "id": "7",
        "name": "Bermuda 7",
        "slug": "bermuda-7",
        "size": "M",
        "quantity": 16,
        "category": "Bermudas",
        "image": "/products/bermuda07.jpg",
        "price": 109.99,
        "description": "Bermuda 7 com estilo moderno e confortável.",
        "rating": 4.6
      },
      {
        "id": "8",
        "name": "Bermuda 8",
        "slug": "bermuda-8",
        "size": "M",
        "quantity": 17,
        "category": "Bermudas",
        "image": "/products/bermuda08.jpg",
        "price": 114.99,
        "description": "Bermuda 8 com estilo moderno e confortável.",
        "rating": 4.7
      },
      {
        "id": "9",
        "name": "Bermuda 9",
        "slug": "bermuda-9",
        "size": "M",
        "quantity": 18,
        "category": "Bermudas",
        "image": "/products/bermuda09.jpg",
        "price": 119.99,
        "description": "Bermuda 9 com estilo moderno e confortável.",
        "rating": 4.8
      },
      {
        "id": "10",
        "name": "Bermuda 10",
        "slug": "bermuda-10",
        "size": "M",
        "quantity": 19,
        "category": "Bermudas",
        "image": "/products/bermuda10.jpg",
        "price": 124.99,
        "description": "Bermuda 10 com estilo moderno e confortável.",
        "rating": 4.9
      },
      {
        "id": "11",
        "name": "Blusa 1",
        "slug": "blusa-1",
        "size": "P",
        "quantity": 15,
        "category": "Blusas",
        "image": "/products/blusa01.jpg",
        "price": 59.99,
        "description": "Blusa 1 com design elegante e leve.",
        "rating": 4.4
      },
      {
        "id": "12",
        "name": "Blusa 2",
        "slug": "blusa-2",
        "size": "P",
        "quantity": 16,
        "category": "Blusas",
        "image": "/products/blusa02.jpg",
        "price": 65.99000000000001,
        "description": "Blusa 2 com design elegante e leve.",
        "rating": 4.5
      },
      {
        "id": "13",
        "name": "Blusa 3",
        "slug": "blusa-3",
        "size": "P",
        "quantity": 17,
        "category": "Blusas",
        "image": "/products/blusa03.jpg",
        "price": 71.99000000000001,
        "description": "Blusa 3 com design elegante e leve.",
        "rating": 4.6000000000000005
      },
      {
        "id": "14",
        "name": "Blusa 4",
        "slug": "blusa-4",
        "size": "P",
        "quantity": 18,
        "category": "Blusas",
        "image": "/products/blusa04.jpg",
        "price": 77.99000000000001,
        "description": "Blusa 4 com design elegante e leve.",
        "rating": 4.7
      },
      {
        "id": "15",
        "name": "Blusa 5",
        "slug": "blusa-5",
        "size": "P",
        "quantity": 19,
        "category": "Blusas",
        "image": "/products/blusa05.jpg",
        "price": 83.99000000000001,
        "description": "Blusa 5 com design elegante e leve.",
        "rating": 4.800000000000001
      },
      {
        "id": "16",
        "name": "Blusa 6",
        "slug": "blusa-6",
        "size": "P",
        "quantity": 20,
        "category": "Blusas",
        "image": "/products/blusa06.jpg",
        "price": 89.99000000000001,
        "description": "Blusa 6 com design elegante e leve.",
        "rating": 4.4
      },
      {
        "id": "17",
        "name": "Blusa 7",
        "slug": "blusa-7",
        "size": "P",
        "quantity": 21,
        "category": "Blusas",
        "image": "/products/blusa07.jpg",
        "price": 95.99000000000001,
        "description": "Blusa 7 com design elegante e leve.",
        "rating": 4.5
      },
      {
        "id": "18",
        "name": "Blusa 8",
        "slug": "blusa-8",
        "size": "P",
        "quantity": 22,
        "category": "Blusas",
        "image": "/products/blusa08.jpg",
        "price": 101.99000000000001,
        "description": "Blusa 8 com design elegante e leve.",
        "rating": 4.6000000000000005
      },
      {
        "id": "19",
        "name": "Blusa 9",
        "slug": "blusa-9",
        "size": "P",
        "quantity": 23,
        "category": "Blusas",
        "image": "/products/blusa09.jpg",
        "price": 107.99000000000001,
        "description": "Blusa 9 com design elegante e leve.",
        "rating": 4.7
      },
      {
        "id": "20",
        "name": "Blusa 10",
        "slug": "blusa-10",
        "size": "P",
        "quantity": 24,
        "category": "Blusas",
        "image": "/products/blusa10.jpg",
        "price": 113.99000000000001,
        "description": "Blusa 10 com design elegante e leve.",
        "rating": 4.800000000000001
      },
      {
        "id": "21",
        "name": "Calça 1",
        "slug": "calca-1",
        "size": "G",
        "quantity": 12,
        "category": "Calças",
        "image": "/products/calca01.jpg",
        "price": 99.99,
        "description": "Calça 1 confortável e versátil.",
        "rating": 4.6
      },
      {
        "id": "22",
        "name": "Calça 2",
        "slug": "calca-2",
        "size": "G",
        "quantity": 13,
        "category": "Calças",
        "image": "/products/calca02.jpg",
        "price": 107.99,
        "description": "Calça 2 confortável e versátil.",
        "rating": 4.699999999999999
      },
      {
        "id": "23",
        "name": "Calça 3",
        "slug": "calca-3",
        "size": "G",
        "quantity": 14,
        "category": "Calças",
        "image": "/products/calca03.jpg",
        "price": 115.99,
        "description": "Calça 3 confortável e versátil.",
        "rating": 4.8
      },
      {
        "id": "24",
        "name": "Calça 4",
        "slug": "calca-4",
        "size": "G",
        "quantity": 15,
        "category": "Calças",
        "image": "/products/calca04.jpg",
        "price": 123.99,
        "description": "Calça 4 confortável e versátil.",
        "rating": 4.8999999999999995
      },
      {
        "id": "25",
        "name": "Calça 5",
        "slug": "calca-5",
        "size": "G",
        "quantity": 16,
        "category": "Calças",
        "image": "/products/calca05.jpg",
        "price": 131.99,
        "description": "Calça 5 confortável e versátil.",
        "rating": 5.0
      },
      {
        "id": "26",
        "name": "Calça 6",
        "slug": "calca-6",
        "size": "G",
        "quantity": 17,
        "category": "Calças",
        "image": "/products/calca06.jpg",
        "price": 139.99,
        "description": "Calça 6 confortável e versátil.",
        "rating": 4.6
      },
      {
        "id": "27",
        "name": "Calça 7",
        "slug": "calca-7",
        "size": "G",
        "quantity": 18,
        "category": "Calças",
        "image": "/products/calca07.jpg",
        "price": 147.99,
        "description": "Calça 7 confortável e versátil.",
        "rating": 4.699999999999999
      },
      {
        "id": "28",
        "name": "Calça 8",
        "slug": "calca-8",
        "size": "G",
        "quantity": 19,
        "category": "Calças",
        "image": "/products/calca08.jpg",
        "price": 155.99,
        "description": "Calça 8 confortável e versátil.",
        "rating": 4.8
      },
      {
        "id": "29",
        "name": "Calça 9",
        "slug": "calca-9",
        "size": "G",
        "quantity": 20,
        "category": "Calças",
        "image": "/products/calca09.jpg",
        "price": 163.99,
        "description": "Calça 9 confortável e versátil.",
        "rating": 4.8999999999999995
      },
      {
        "id": "30",
        "name": "Calça 10",
        "slug": "calca-10",
        "size": "G",
        "quantity": 21,
        "category": "Calças",
        "image": "/products/calca10.jpg",
        "price": 171.99,
        "description": "Calça 10 confortável e versátil.",
        "rating": 5.0
      },
      {
        "id": "51",
        "name": "Saia 1",
        "slug": "saia-1",
        "size": "M",
        "quantity": 18,
        "category": "Saias",
        "image": "/products/saia01.jpg",
        "price": 69.99,
        "description": "Saia 1 elegante e leve.",
        "rating": 4.6
      },
      {
        "id": "52",
        "name": "Saia 2",
        "slug": "saia-2",
        "size": "M",
        "quantity": 19,
        "category": "Saias",
        "image": "/products/saia02.jpg",
        "price": 74.99,
        "description": "Saia 2 elegante e leve.",
        "rating": 4.699999999999999
      },
      {
        "id": "53",
        "name": "Saia 3",
        "slug": "saia-3",
        "size": "M",
        "quantity": 20,
        "category": "Saias",
        "image": "/products/saia03.jpg",
        "price": 79.99,
        "description": "Saia 3 elegante e leve.",
        "rating": 4.8
      },
      {
        "id": "54",
        "name": "Saia 4",
        "slug": "saia-4",
        "size": "M",
        "quantity": 21,
        "category": "Saias",
        "image": "/products/saia04.jpg",
        "price": 84.99,
        "description": "Saia 4 elegante e leve.",
        "rating": 4.8999999999999995
      },
      {
        "id": "55",
        "name": "Saia 5",
        "slug": "saia-5",
        "size": "M",
        "quantity": 22,
        "category": "Saias",
        "image": "/products/saia05.jpg",
        "price": 89.99,
        "description": "Saia 5 elegante e leve.",
        "rating": 5.0
      },
      {
        "id": "56",
        "name": "Saia 6",
        "slug": "saia-6",
        "size": "M",
        "quantity": 23,
        "category": "Saias",
        "image": "/products/saia06.jpg",
        "price": 94.99,
        "description": "Saia 6 elegante e leve.",
        "rating": 4.6
      },
      {
        "id": "57",
        "name": "Saia 7",
        "slug": "saia-7",
        "size": "M",
        "quantity": 24,
        "category": "Saias",
        "image": "/products/saia07.jpg",
        "price": 99.99,
        "description": "Saia 7 elegante e leve.",
        "rating": 4.699999999999999
      },
      {
        "id": "58",
        "name": "Saia 8",
        "slug": "saia-8",
        "size": "M",
        "quantity": 25,
        "category": "Saias",
        "image": "/products/saia08.jpg",
        "price": 104.99,
        "description": "Saia 8 elegante e leve.",
        "rating": 4.8
      },
      {
        "id": "59",
        "name": "Saia 9",
        "slug": "saia-9",
        "size": "M",
        "quantity": 26,
        "category": "Saias",
        "image": "/products/saia09.jpg",
        "price": 109.99,
        "description": "Saia 9 elegante e leve.",
        "rating": 4.8999999999999995
      },
      {
        "id": "60",
        "name": "Saia 10",
        "slug": "saia-10",
        "size": "M",
        "quantity": 27,
        "category": "Saias",
        "image": "/products/saia10.jpg",
        "price": 114.99,
        "description": "Saia 10 elegante e leve.",
        "rating": 5.0
      },
      {
        "id": "61",
        "name": "Casaco 1",
        "slug": "casaco-1",
        "size": "G",
        "quantity": 14,
        "category": "Casacos",
        "image": "/products/casaco01.jpg",
        "price": 199.99,
        "description": "Casaco 1 para o frio com estilo.",
        "rating": 4.8
      },
      {
        "id": "62",
        "name": "Casaco 2",
        "slug": "casaco-2",
        "size": "G",
        "quantity": 15,
        "category": "Casacos",
        "image": "/products/casaco02.jpg",
        "price": 214.99,
        "description": "Casaco 2 para o frio com estilo.",
        "rating": 4.8999999999999995
      },
      {
        "id": "63",
        "name": "Casaco 3",
        "slug": "casaco-3",
        "size": "G",
        "quantity": 16,
        "category": "Casacos",
        "image": "/products/casaco03.jpg",
        "price": 229.99,
        "description": "Casaco 3 para o frio com estilo.",
        "rating": 5.0
      },
      {
        "id": "64",
        "name": "Casaco 4",
        "slug": "casaco-4",
        "size": "G",
        "quantity": 17,
        "category": "Casacos",
        "image": "/products/casaco04.jpg",
        "price": 244.99,
        "description": "Casaco 4 para o frio com estilo.",
        "rating": 5.1
      },
      {
        "id": "65",
        "name": "Casaco 5",
        "slug": "casaco-5",
        "size": "G",
        "quantity": 18,
        "category": "Casacos",
        "image": "/products/casaco05.jpg",
        "price": 259.99,
        "description": "Casaco 5 para o frio com estilo.",
        "rating": 5.2
      },
      {
        "id": "66",
        "name": "Casaco 6",
        "slug": "casaco-6",
        "size": "G",
        "quantity": 19,
        "category": "Casacos",
        "image": "/products/casaco06.jpg",
        "price": 274.99,
        "description": "Casaco 6 para o frio com estilo.",
        "rating": 4.8
      },
      {
        "id": "67",
        "name": "Casaco 7",
        "slug": "casaco-7",
        "size": "G",
        "quantity": 20,
        "category": "Casacos",
        "image": "/products/casaco07.jpg",
        "price": 289.99,
        "description": "Casaco 7 para o frio com estilo.",
        "rating": 4.8999999999999995
      },
      {
        "id": "68",
        "name": "Casaco 8",
        "slug": "casaco-8",
        "size": "G",
        "quantity": 21,
        "category": "Casacos",
        "image": "/products/casaco08.jpg",
        "price": 304.99,
        "description": "Casaco 8 para o frio com estilo.",
        "rating": 5.0
      },
      {
        "id": "69",
        "name": "Casaco 9",
        "slug": "casaco-9",
        "size": "G",
        "quantity": 22,
        "category": "Casacos",
        "image": "/products/casaco09.jpg",
        "price": 319.99,
        "description": "Casaco 9 para o frio com estilo.",
        "rating": 5.1
      },
      {
        "id": "70",
        "name": "Casaco 10",
        "slug": "casaco-10",
        "size": "G",
        "quantity": 23,
        "category": "Casacos",
        "image": "/products/casaco10.jpg",
        "price": 334.99,
        "description": "Casaco 10 para o frio com estilo.",
        "rating": 5.2
      },
      {
        "id": "71",
        "name": "Vestido 1",
        "slug": "vestido-1",
        "size": "P",
        "quantity": 16,
        "category": "Vestidos",
        "image": "/products/vestido01.jpg",
        "price": 119.99,
        "description": "Vestido 1 perfeito para ocasiões especiais.",
        "rating": 4.9
      },
      {
        "id": "72",
        "name": "Vestido 2",
        "slug": "vestido-2",
        "size": "P",
        "quantity": 17,
        "category": "Vestidos",
        "image": "/products/vestido02.jpg",
        "price": 129.99,
        "description": "Vestido 2 perfeito para ocasiões especiais.",
        "rating": 5.0
      },
      {
        "id": "73",
        "name": "Vestido 3",
        "slug": "vestido-3",
        "size": "P",
        "quantity": 18,
        "category": "Vestidos",
        "image": "/products/vestido03.jpg",
        "price": 139.99,
        "description": "Vestido 3 perfeito para ocasiões especiais.",
        "rating": 5.1000000000000005
      },
      {
        "id": "74",
        "name": "Vestido 4",
        "slug": "vestido-4",
        "size": "P",
        "quantity": 19,
        "category": "Vestidos",
        "image": "/products/vestido04.jpg",
        "price": 149.99,
        "description": "Vestido 4 perfeito para ocasiões especiais.",
        "rating": 5.2
      },
      {
        "id": "75",
        "name": "Vestido 5",
        "slug": "vestido-5",
        "size": "P",
        "quantity": 20,
        "category": "Vestidos",
        "image": "/products/vestido05.jpg",
        "price": 159.99,
        "description": "Vestido 5 perfeito para ocasiões especiais.",
        "rating": 5.300000000000001
      },
      {
        "id": "76",
        "name": "Vestido 6",
        "slug": "vestido-6",
        "size": "P",
        "quantity": 21,
        "category": "Vestidos",
        "image": "/products/vestido06.jpg",
        "price": 169.99,
        "description": "Vestido 6 perfeito para ocasiões especiais.",
        "rating": 4.9
      },
      {
        "id": "77",
        "name": "Vestido 7",
        "slug": "vestido-7",
        "size": "P",
        "quantity": 22,
        "category": "Vestidos",
        "image": "/products/vestido07.jpg",
        "price": 179.99,
        "description": "Vestido 7 perfeito para ocasiões especiais.",
        "rating": 5.0
      },
      {
        "id": "78",
        "name": "Vestido 8",
        "slug": "vestido-8",
        "size": "P",
        "quantity": 23,
        "category": "Vestidos",
        "image": "/products/vestido08.jpg",
        "price": 189.99,
        "description": "Vestido 8 perfeito para ocasiões especiais.",
        "rating": 5.1000000000000005
      },
      {
        "id": "79",
        "name": "Vestido 9",
        "slug": "vestido-9",
        "size": "P",
        "quantity": 24,
        "category": "Vestidos",
        "image": "/products/vestido09.jpg",
        "price": 199.99,
        "description": "Vestido 9 perfeito para ocasiões especiais.",
        "rating": 5.2
      },
      {
        "id": "80",
        "name": "Vestido 10",
        "slug": "vestido-10",
        "size": "P",
        "quantity": 25,
        "category": "Vestidos",
        "image": "/products/vestido10.jpg",
        "price": 209.99,
        "description": "Vestido 10 perfeito para ocasiões especiais.",
        "rating": 5.3
      }
  ],
}

export default data;