
import { PrismaClient } from "@prisma/client";
import type { Product } from "@/lib/types";

const prisma = new PrismaClient();

export const products: Product[] = [
  {
    id: "1",
    name: "Bermuda 1",
    slug: "bermuda-1",
    size: "M",
    quantity: 10,
    category: "Bermudas",
    image: "https://utfs.io/f/5mtAsAQDoNVdzrsFqbW6TLW359m4tynvSN02Ap1IlXBs8oEH",
    price: 79.99,
    description: "Bermuda 1 com estilo moderno e confortável.",
    rating: 4.5,
  },
  {
    id: "2",
    name: "Bermuda 2",
    slug: "bermuda-2",
    size: "M",
    quantity: 11,
    category: "Bermudas",
    image: "https://utfs.io/f/5mtAsAQDoNVdMIVMvBKiQ2bczoCjkpeXZ0DET8BxKHFVy9us",
    price: 84.99,
    description: "Bermuda 2 com estilo moderno e confortável.",
    rating: 4.6,
  },
  {
    id: "3",
    name: "Bermuda 3",
    slug: "bermuda-3",
    size: "M",
    quantity: 12,
    category: "Bermudas",
    image: "https://utfs.io/f/5mtAsAQDoNVdFwbKpEZQ9homzstNZS3cMDnIPWqf5AECL4Ya",
    price: 89.99,
    description: "Bermuda 3 com estilo moderno e confortável.",
    rating: 4.7,
  },
  {
    id: "4",
    name: "Bermuda 4",
    slug: "bermuda-4",
    size: "M",
    quantity: 13,
    category: "Bermudas",
    image: "https://utfs.io/f/5mtAsAQDoNVdEUO9lLzNH8RgnYW0ZbduF2IwJ5Gvpsoc9kBD",
    price: 94.99,
    description: "Bermuda 4 com estilo moderno e confortável.",
    rating: 4.8,
  },
  {
    id: "5",
    name: "Bermuda 5",
    slug: "bermuda-5",
    size: "M",
    quantity: 14,
    category: "Bermudas",
    image: "https://utfs.io/f/5mtAsAQDoNVdHn5280iCvWlbOMF8YmXR1zuxD6GfAoVUswre",
    price: 99.99,
    description: "Bermuda 5 com estilo moderno e confortável.",
    rating: 4.9,
  },
  {
    id: "6",
    name: "Bermuda 6",
    slug: "bermuda-6",
    size: "M",
    quantity: 15,
    category: "Bermudas",
    image: "https://utfs.io/f/5mtAsAQDoNVdHlsvpdiCvWlbOMF8YmXR1zuxD6GfAoVUswre",
    price: 104.99,
    description: "Bermuda 6 com estilo moderno e confortável.",
    rating: 4.5,
  },
  {
    id: "7",
    name: "Bermuda 7",
    slug: "bermuda-7",
    size: "M",
    quantity: 16,
    category: "Bermudas",
    image: "https://utfs.io/f/5mtAsAQDoNVd0LLmi1pH68AU172BrFYkhW3S9OspT5vgVenG",
    price: 109.99,
    description: "Bermuda 7 com estilo moderno e confortável.",
    rating: 4.6,
  },
  {
    id: "8",
    name: "Bermuda 8",
    slug: "bermuda-8",
    size: "M",
    quantity: 17,
    category: "Bermudas",
    image: "https://utfs.io/f/5mtAsAQDoNVdWSNGxDRZL26svVc9hCSJdjxD0aKFgoiBUNOG",
    price: 114.99,
    description: "Bermuda 8 com estilo moderno e confortável.",
    rating: 4.7,
  },
  {
    id: "9",
    name: "Bermuda 9",
    slug: "bermuda-9",
    size: "M",
    quantity: 18,
    category: "Bermudas",
    image: "https://utfs.io/f/5mtAsAQDoNVdm2hYz0HzyiST2joerRWH51nKwU89baQGPC43",
    price: 119.99,
    description: "Bermuda 9 com estilo moderno e confortável.",
    rating: 4.8,
  },
  {
    id: "10",
    name: "Bermuda 10",
    slug: "bermuda-10",
    size: "M",
    quantity: 19,
    category: "Bermudas",
    image: "https://utfs.io/f/5mtAsAQDoNVdBFnoImPGyERNJwPMYSmQ5nsFqovdLzVlH1tO",
    price: 124.99,
    description: "Bermuda 10 com estilo moderno e confortável.",
    rating: 4.9,
  },
  {
    id: "11",
    name: "Blusa 1",
    slug: "blusa-1",
    size: "P",
    quantity: 15,
    category: "Blusas",
    image: "https://utfs.io/f/5mtAsAQDoNVd3lmQRpwdsdheZNWkG4YVvOugmcHwFy2oPJA6",
    price: 59.99,
    description: "Blusa 1 com design elegante e leve.",
    rating: 4.4,
  },
  {
    id: "12",
    name: "Blusa 2",
    slug: "blusa-2",
    size: "P",
    quantity: 16,
    category: "Blusas",
    image: "https://utfs.io/f/5mtAsAQDoNVdyNwVEW6B3QKHMax1NcztX9CTwfGJmSRIO5bl",
    price: 65.99000000000001,
    description: "Blusa 2 com design elegante e leve.",
    rating: 4.5,
  },
  {
    id: "13",
    name: "Blusa 3",
    slug: "blusa-3",
    size: "P",
    quantity: 17,
    category: "Blusas",
    image: "https://utfs.io/f/5mtAsAQDoNVdOsZIc9oLVnA2C178wsEhF94YJIkLMN6gecXt",
    price: 71.99000000000001,
    description: "Blusa 3 com design elegante e leve.",
    rating: 4.6000000000000005,
  },
  {
    id: "14",
    name: "Blusa 4",
    slug: "blusa-4",
    size: "P",
    quantity: 18,
    category: "Blusas",
    image: "https://utfs.io/f/5mtAsAQDoNVdm0PR83bHzyiST2joerRWH51nKwU89baQGPC4",
    price: 77.99000000000001,
    description: "Blusa 4 com design elegante e leve.",
    rating: 4.7,
  },
  {
    id: "15",
    name: "Blusa 5",
    slug: "blusa-5",
    size: "P",
    quantity: 19,
    category: "Blusas",
    image: "https://utfs.io/f/5mtAsAQDoNVd0ShRcLpH68AU172BrFYkhW3S9OspT5vgVenG",
    price: 83.99000000000001,
    description: "Blusa 5 com design elegante e leve.",
    rating: 4.800000000000001,
  },
  {
    id: "16",
    name: "Blusa 6",
    slug: "blusa-6",
    size: "P",
    quantity: 20,
    category: "Blusas",
    image: "https://utfs.io/f/5mtAsAQDoNVdpLUsjnk9wB1DHrkmYyZI9xvtgKo8UzA5XuaS",
    price: 89.99000000000001,
    description: "Blusa 6 com design elegante e leve.",
    rating: 4.4,
  },
  {
    id: "17",
    name: "Blusa 7",
    slug: "blusa-7",
    size: "P",
    quantity: 21,
    category: "Blusas",
    image: "https://utfs.io/f/5mtAsAQDoNVdcFqmLLZ4NELnzBe4frOiWu2loM0GP6JVbZwD",
    price: 95.99000000000001,
    description: "Blusa 7 com design elegante e leve.",
    rating: 4.5,
  },
  {
    id: "18",
    name: "Blusa 8",
    slug: "blusa-8",
    size: "P",
    quantity: 22,
    category: "Blusas",
    image: "https://utfs.io/f/5mtAsAQDoNVdLUwjPmvBaNK5qFxVDwbIEhyWlSGnuMkZvefo",
    price: 101.99000000000001,
    description: "Blusa 8 com design elegante e leve.",
    rating: 4.6000000000000005,
  },
  {
    id: "19",
    name: "Blusa 9",
    slug: "blusa-9",
    size: "P",
    quantity: 23,
    category: "Blusas",
    image: "https://utfs.io/f/5mtAsAQDoNVdz57btG5W6TLW359m4tynvSN02Ap1IlXBs8oE",
    price: 107.99000000000001,
    description: "Blusa 9 com design elegante e leve.",
    rating: 4.7,
  },
  {
    id: "20",
    name: "Blusa 10",
    slug: "blusa-10",
    size: "P",
    quantity: 24,
    category: "Blusas",
    image: "https://utfs.io/f/5mtAsAQDoNVdgffNHPRJ1kacrtyCQ7DoRm3nXBvOGJUpuS49",
    price: 113.99000000000001,
    description: "Blusa 10 com design elegante e leve.",
    rating: 4.800000000000001,
  },
  {
    id: "21",
    name: "Calça 1",
    slug: "calca-1",
    size: "G",
    quantity: 12,
    category: "Calças",
    image: "https://utfs.io/f/5mtAsAQDoNVdOzEz0oLVnA2C178wsEhF94YJIkLMN6gecXti",
    price: 99.99,
    description: "Calça 1 confortável e versátil.",
    rating: 4.6,
  },
  {
    id: "22",
    name: "Calça 2",
    slug: "calca-2",
    size: "G",
    quantity: 13,
    category: "Calças",
    image: "https://utfs.io/f/5mtAsAQDoNVdLhekEVvBaNK5qFxVDwbIEhyWlSGnuMkZvefo",
    price: 107.99,
    description: "Calça 2 confortável e versátil.",
    rating: 4.699999999999999,
  },
  {
    id: "23",
    name: "Calça 3",
    slug: "calca-3",
    size: "G",
    quantity: 14,
    category: "Calças",
    image: "https://utfs.io/f/5mtAsAQDoNVdGkC3NRb4FZUPi3ocSJ6IMAqzrtpHxRWugBC7",
    price: 115.99,
    description: "Calça 3 confortável e versátil.",
    rating: 4.8,
  },
  {
    id: "24",
    name: "Calça 4",
    slug: "calca-4",
    size: "G",
    quantity: 15,
    category: "Calças",
    image: "https://utfs.io/f/5mtAsAQDoNVdNVB3S2MpAd9bfM0zuhPSoECY3rqQHg1O7viK",
    price: 123.99,
    description: "Calça 4 confortável e versátil.",
    rating: 4.8999999999999995,
  },
  {
    id: "25",
    name: "Calça 5",
    slug: "calca-5",
    size: "G",
    quantity: 16,
    category: "Calças",
    image: "https://utfs.io/f/5mtAsAQDoNVdQsgJISN3VgtvbXqpjAOw5ucYWh0GPmeLsF47",
    price: 131.99,
    description: "Calça 5 confortável e versátil.",
    rating: 5.0,
  },
  {
    id: "26",
    name: "Calça 6",
    slug: "calca-6",
    size: "G",
    quantity: 17,
    category: "Calças",
    image: "https://utfs.io/f/5mtAsAQDoNVdDkZ2Cf7DVFfCpS0s3crWRL4g5YdqUn9bAw6h",
    price: 139.99,
    description: "Calça 6 confortável e versátil.",
    rating: 4.6,
  },
  {
    id: "27",
    name: "Calça 7",
    slug: "calca-7",
    size: "G",
    quantity: 18,
    category: "Calças",
    image: "https://utfs.io/f/5mtAsAQDoNVddB5ZRQklJy7a4PFCjZKSrm6u8vWXD1tw9ipT",
    price: 147.99,
    description: "Calça 7 confortável e versátil.",
    rating: 4.699999999999999,
  },
  {
    id: "28",
    name: "Calça 8",
    slug: "calca-8",
    size: "G",
    quantity: 19,
    category: "Calças",
    image: "https://utfs.io/f/5mtAsAQDoNVdh5WlRwt3Wejm7NcyD1Vi2fpw65b0K8lQRua4",
    price: 155.99,
    description: "Calça 8 confortável e versátil.",
    rating: 4.8,
  },
  {
    id: "29",
    name: "Calça 9",
    slug: "calca-9",
    size: "G",
    quantity: 20,
    category: "Calças",
    image: "https://utfs.io/f/5mtAsAQDoNVdppRtL09wB1DHrkmYyZI9xvtgKo8UzA5XuaS6",
    price: 163.99,
    description: "Calça 9 confortável e versátil.",
    rating: 4.8999999999999995,
  },
  {
    id: "30",
    name: "Calça 10",
    slug: "calca-10",
    size: "G",
    quantity: 21,
    category: "Calças",
    image: "https://utfs.io/f/5mtAsAQDoNVdDguuSkF7DVFfCpS0s3crWRL4g5YdqUn9bAw6",
    price: 171.99,
    description: "Calça 10 confortável e versátil.",
    rating: 5.0,
  },
  {
    id: "31",
    name: "Saia 1",
    slug: "saia-1",
    size: "M",
    quantity: 18,
    category: "Saias",
    image: "https://utfs.io/f/5mtAsAQDoNVdtZYCzV8azkBmsRHjS7WyVJfZpEAui85UF1Dq",
    price: 69.99,
    description: "Saia 1 elegante e leve.",
    rating: 4.6,
  },
  {
    id: "32",
    name: "Saia 2",
    slug: "saia-2",
    size: "M",
    quantity: 19,
    category: "Saias",
    image: "https://utfs.io/f/5mtAsAQDoNVdWvolDpRZL26svVc9hCSJdjxD0aKFgoiBUNOG",
    price: 74.99,
    description: "Saia 2 elegante e leve.",
    rating: 4.699999999999999,
  },
  {
    id: "33",
    name: "Saia 3",
    slug: "saia-3",
    size: "M",
    quantity: 20,
    category: "Saias",
    image: "https://utfs.io/f/5mtAsAQDoNVdyPyjkY6B3QKHMax1NcztX9CTwfGJmSRIO5bl",
    price: 79.99,
    description: "Saia 3 elegante e leve.",
    rating: 4.8,
  },
  {
    id: "34",
    name: "Saia 4",
    slug: "saia-4",
    size: "M",
    quantity: 21,
    category: "Saias",
    image: "https://utfs.io/f/5mtAsAQDoNVd7YwoHauRlp8HfYVo7rAIudN0UF6cXzagZjTQ",
    price: 84.99,
    description: "Saia 4 elegante e leve.",
    rating: 4.8999999999999995,
  },
  {
    id: "35",
    name: "Saia 5",
    slug: "saia-5",
    size: "M",
    quantity: 22,
    category: "Saias",
    image: "https://utfs.io/f/5mtAsAQDoNVdzCKsnsW6TLW359m4tynvSN02Ap1IlXBs8oEH",
    price: 89.99,
    description: "Saia 5 elegante e leve.",
    rating: 5.0,
  },
  {
    id: "36",
    name: "Saia 6",
    slug: "saia-6",
    size: "M",
    quantity: 23,
    category: "Saias",
    image: "https://utfs.io/f/5mtAsAQDoNVd6UQoQnEieVQOFwnUC1puzSAXIRPBMvfl05Zc",
    price: 94.99,
    description: "Saia 6 elegante e leve.",
    rating: 4.6,
  },
  {
    id: "37",
    name: "Saia 7",
    slug: "saia-7",
    size: "M",
    quantity: 24,
    category: "Saias",
    image: "https://utfs.io/f/5mtAsAQDoNVdcVlSlG4NELnzBe4frOiWu2loM0GP6JVbZwDp",
    price: 99.99,
    description: "Saia 7 elegante e leve.",
    rating: 4.699999999999999,
  },
  {
    id: "38",
    name: "Saia 8",
    slug: "saia-8",
    size: "M",
    quantity: 25,
    category: "Saias",
    image: "https://utfs.io/f/5mtAsAQDoNVdzzzJwhW6TLW359m4tynvSN02Ap1IlXBs8oEH",
    price: 104.99,
    description: "Saia 8 elegante e leve.",
    rating: 4.8,
  },
  {
    id: "39",
    name: "Saia 9",
    slug: "saia-9",
    size: "M",
    quantity: 26,
    category: "Saias",
    image: "https://utfs.io/f/5mtAsAQDoNVdGNx70Ob4FZUPi3ocSJ6IMAqzrtpHxRWugBC7",
    price: 109.99,
    description: "Saia 9 elegante e leve.",
    rating: 4.8999999999999995,
  },
  {
    id: "40",
    name: "Saia 10",
    slug: "saia-10",
    size: "M",
    quantity: 27,
    category: "Saias",
    image: "https://utfs.io/f/5mtAsAQDoNVdCIB8IPnJPxHLlG50u1ADBjyXMKgp3Zotbiws",
    price: 114.99,
    description: "Saia 10 elegante e leve.",
    rating: 5.0,
  },
  {
    id: "41",
    name: "Casaco 1",
    slug: "casaco-1",
    size: "G",
    quantity: 14,
    category: "Casacos",
    image: "https://utfs.io/f/5mtAsAQDoNVd7lCJIvuRlp8HfYVo7rAIudN0UF6cXzagZjTQ",
    price: 199.99,
    description: "Casaco 1 para o frio com estilo.",
    rating: 4.8,
  },
  {
    id: "42",
    name: "Casaco 2",
    slug: "casaco-2",
    size: "G",
    quantity: 15,
    category: "Casacos",
    image: "https://utfs.io/f/5mtAsAQDoNVdCU9TQ3nJPxHLlG50u1ADBjyXMKgp3Zotbiws",
    price: 214.99,
    description: "Casaco 2 para o frio com estilo.",
    rating: 4.8999999999999995,
  },
  {
    id: "43",
    name: "Casaco 3",
    slug: "casaco-3",
    size: "G",
    quantity: 16,
    category: "Casacos",
    image: "https://utfs.io/f/5mtAsAQDoNVdmPmnYQHzyiST2joerRWH51nKwU89baQGPC43",
    price: 229.99,
    description: "Casaco 3 para o frio com estilo.",
    rating: 5.0,
  },
  {
    id: "44",
    name: "Casaco 4",
    slug: "casaco-4",
    size: "G",
    quantity: 17,
    category: "Casacos",
    image: "https://utfs.io/f/5mtAsAQDoNVd8kpY3CyeWYNo2CfSyah5Hq63QsdZktEzGMK1",
    price: 244.99,
    description: "Casaco 4 para o frio com estilo.",
    rating: 5.1,
  },
  {
    id: "45",
    name: "Casaco 5",
    slug: "casaco-5",
    size: "G",
    quantity: 18,
    category: "Casacos",
    image: "https://utfs.io/f/5mtAsAQDoNVd64eZgHEieVQOFwnUC1puzSAXIRPBMvfl05Zc",
    price: 259.99,
    description: "Casaco 5 para o frio com estilo.",
    rating: 5.2,
  },
  {
    id: "46",
    name: "Casaco 6",
    slug: "casaco-6",
    size: "G",
    quantity: 19,
    category: "Casacos",
    image: "https://utfs.io/f/5mtAsAQDoNVd0OZgKRTpH68AU172BrFYkhW3S9OspT5vgVen",
    price: 274.99,
    description: "Casaco 6 para o frio com estilo.",
    rating: 4.8,
  },
  {
    id: "47",
    name: "Casaco 7",
    slug: "casaco-7",
    size: "G",
    quantity: 20,
    category: "Casacos",
    image: "https://utfs.io/f/5mtAsAQDoNVdpLxEfSz9wB1DHrkmYyZI9xvtgKo8UzA5XuaS",
    price: 289.99,
    description: "Casaco 7 para o frio com estilo.",
    rating: 4.8999999999999995,
  },
  {
    id: "48",
    name: "Casaco 8",
    slug: "casaco-8",
    size: "G",
    quantity: 21,
    category: "Casacos",
    image: "https://utfs.io/f/5mtAsAQDoNVdcjq30P4NELnzBe4frOiWu2loM0GP6JVbZwDp",
    price: 304.99,
    description: "Casaco 8 para o frio com estilo.",
    rating: 5.0,
  },
  {
    id: "49",
    name: "Casaco 9",
    slug: "casaco-9",
    size: "G",
    quantity: 22,
    category: "Casacos",
    image: "https://utfs.io/f/5mtAsAQDoNVdNutFjlMpAd9bfM0zuhPSoECY3rqQHg1O7viK",
    price: 319.99,
    description: "Casaco 9 para o frio com estilo.",
    rating: 5.1,
  },
  {
    id: "50",
    name: "Casaco 10",
    slug: "casaco-10",
    size: "G",
    quantity: 23,
    category: "Casacos",
    image: "https://utfs.io/f/5mtAsAQDoNVdyPBkql6B3QKHMax1NcztX9CTwfGJmSRIO5bl",
    price: 334.99,
    description: "Casaco 10 para o frio com estilo.",
    rating: 5.2,
  },
  {
    id: "51",
    name: "Vestido 1",
    slug: "vestido-1",
    size: "P",
    quantity: 16,
    category: "Vestidos",
    image: "https://utfs.io/f/5mtAsAQDoNVd8ASEv3yeWYNo2CfSyah5Hq63QsdZktEzGMK1",
    price: 119.99,
    description: "Vestido 1 perfeito para ocasiões especiais.",
    rating: 4.9,
  },
  {
    id: "52",
    name: "Vestido 2",
    slug: "vestido-2",
    size: "P",
    quantity: 17,
    category: "Vestidos",
    image: "https://utfs.io/f/5mtAsAQDoNVdLcBtfncvBaNK5qFxVDwbIEhyWlSGnuMkZvef",
    price: 129.99,
    description: "Vestido 2 perfeito para ocasiões especiais.",
    rating: 5.0,
  },
  {
    id: "53",
    name: "Vestido 3",
    slug: "vestido-3",
    size: "P",
    quantity: 18,
    category: "Vestidos",
    image: "https://utfs.io/f/5mtAsAQDoNVdEpbP78zNH8RgnYW0ZbduF2IwJ5Gvpsoc9kBD",
    price: 139.99,
    description: "Vestido 3 perfeito para ocasiões especiais.",
    rating: 5.1000000000000005,
  },
  {
    id: "54",
    name: "Vestido 4",
    slug: "vestido-4",
    size: "P",
    quantity: 19,
    category: "Vestidos",
    image: "https://utfs.io/f/5mtAsAQDoNVdSoSLfuBjBTxsbyO2PgYEuwKDoVtCFW0qkfAn",
    price: 149.99,
    description: "Vestido 4 perfeito para ocasiões especiais.",
    rating: 5.2,
  },
  {
    id: "55",
    name: "Vestido 5",
    slug: "vestido-5",
    size: "P",
    quantity: 20,
    category: "Vestidos",
    image: "https://utfs.io/f/5mtAsAQDoNVd3louo2dsdheZNWkG4YVvOugmcHwFy2oPJA6Q",
    price: 159.99,
    description: "Vestido 5 perfeito para ocasiões especiais.",
    rating: 5.300000000000001,
  },
  {
    id: "56",
    name: "Vestido 6",
    slug: "vestido-6",
    size: "P",
    quantity: 21,
    category: "Vestidos",
    image: "https://utfs.io/f/5mtAsAQDoNVda7j6OkFnzt3MfRqZywliUbpAoIuea5kYgEhr",
    price: 169.99,
    description: "Vestido 6 perfeito para ocasiões especiais.",
    rating: 4.9,
  },
  {
    id: "57",
    name: "Vestido 7",
    slug: "vestido-7",
    size: "P",
    quantity: 22,
    category: "Vestidos",
    image: "https://utfs.io/f/5mtAsAQDoNVduYLdvtgvfNh0sc83LFj1PIoDmeqaXTKrgBxW",
    price: 179.99,
    description: "Vestido 7 perfeito para ocasiões especiais.",
    rating: 5.0,
  },
  {
    id: "58",
    name: "Vestido 8",
    slug: "vestido-8",
    size: "P",
    quantity: 23,
    category: "Vestidos",
    image: "https://utfs.io/f/5mtAsAQDoNVdsyvqvacVXBZhPY2AFNJL4fkwz7MT5ytgK8cv",
    price: 189.99,
    description: "Vestido 8 perfeito para ocasiões especiais.",
    rating: 5.1000000000000005,
  },
  {
    id: "59",
    name: "Vestido 9",
    slug: "vestido-9",
    size: "P",
    quantity: 24,
    category: "Vestidos",
    image: "https://utfs.io/f/5mtAsAQDoNVdycJtkM6B3QKHMax1NcztX9CTwfGJmSRIO5bl",
    price: 199.99,
    description: "Vestido 9 perfeito para ocasiões especiais.",
    rating: 5.2,
  },
  {
    id: "60",
    name: "Vestido 10",
    slug: "vestido-10",
    size: "P",
    quantity: 25,
    category: "Vestidos",
    image: "https://utfs.io/f/5mtAsAQDoNVdjm9sgkAfdVBwe46b5jvnIzgHZ09TSmtOhRGP",
    price: 209.99,
    description: "Vestido 10 perfeito para ocasiões especiais.",
    rating: 5.3,
  },
];

async function main() {
  try {
    console.log("🌱 Iniciando seed do banco de dados...");
    
    // Limpar dados existentes
    console.log("🧹 Limpando dados existentes...");
    await prisma.product.deleteMany();
    
    // Inserir produtos
    console.log(`💾 Inserindo ${products.length} produtos...`);
    await prisma.product.createMany({
      data: products.map(produto => ({
        id: produto.id,
        name: produto.name,
        slug: produto.slug,
        category: produto.category,
        image: produto.image,
        price: produto.price,
        description: produto.description,
        rating: produto.rating,
        size: produto.size,
        quantity: produto.quantity,
      }))
    });

    console.log("✅ Seed concluído com sucesso!");
  } catch (error) {
    console.error("❌ Erro durante o seed:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

main()
  .catch((error) => {
    console.error("Fatal error:", error);
    process.exit(1);
  });